Areas/Admin/Controllers/TicketsController.cs
#region

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Common;
using Common.Models.Admin.Tickets;
using Common.Models.Admin.Users;
using Common.Models.Admin.ViewModel;
using Common.Providers.Logging;
using Common.Providers.Messages;
using Common.Providers.Roles;
using Common.Providers.Users;
using Common.Repositories;
using EmailTemplate = Common.Providers.Email.EmailTemplate;

#endregion

namespace Kapsters.Areas.Admin.Controllers
{
    public class TicketsController : ApplicationController
    {
        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        [ActionName("_Open-tickets-weergeven")]
        public ActionResult _OpenTicketsWeergeven()
        {
            return View(GetTickets(1));
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        [ActionName("Open-tickets-weergeven")]
        public ActionResult OpenTicketsWeergeven()
        {
            return View();
        }

        [ActionName("_Gesloten-tickets-weergeven")]
        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        public ActionResult _GeslotenTicketsWeergeven()
        {
            return View(GetTickets(2));
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        [ActionName("Gesloten-tickets-weergeven")]
        public ActionResult GeslotenTicketsWeergeven()
        {
            return View();
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        [ActionName("_Behandelde-tickets-weergeven")]
        public ActionResult _BehandeldeTicketsWeergeven()
        {
            return View(GetTickets(1));
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        [ActionName("Behandelde-tickets-weergeven")]
        public ActionResult BehandeldeTicketsWeergeven()
        {
            return View();
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        [ActionName("_Alle-tickets-weergeven")]
        public ActionResult _AlleTicketsWeergeven()
        {
            return View(GetTickets(3));
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        [ActionName("Alle-tickets-weergeven")]
        public ActionResult AlleTicketsWeergeven()
        {
            return View();
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        public ActionResult Toevoegen()
        {
            IEnumerable<UserModelInfo> usersList = UserProvider.GetAllUsers();
            var createTicketModel = new CreateTicketModel();

            foreach (UserModelInfo user in usersList)
            {
                createTicketModel.Users.Add(new SelectListItem
                {
                    Text = user.Firstname + " " + user.Lastname,
                    Value = user.Username
                });
            }
            return View(createTicketModel);
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        [HttpPost]
        public ActionResult Toevoegen(CreateTicketModel createTicketModel)
        {
            if (ModelState.IsValid)
            {
                // Get provider user key
                Guid providerUserKey = UserProvider.GetProviderUserKey(createTicketModel.Username);

                // Initialize ticket repository
                var ticketRepository = new TicketRepository();

                // Initialize ticket reaction repository
                var ticketCommentRepository = new TicketReactieRepository();

                // Add ticket
                ticketRepository.Add(new Ticket
                {
                    DatumOpen = DateTime.Now,
                    Onderwerp = createTicketModel.Subject,
                    Status = 0,
                    TicketGebruikersId = providerUserKey
                });

                // Save ticket
                ticketRepository.Save();

                // Get ticket
                Ticket latestTicket = ticketRepository.GetLastTicket();

                // Add ticket reaction repository
                ticketCommentRepository.Add(new TicketReactie
                {
                    Datum = DateTime.Now,
                    GebruikersId = providerUserKey,
                    Reactie = createTicketModel.Message,
                    TicketID = latestTicket.TicketID
                });

                // Save ticket reaction
                ticketCommentRepository.Save();

                // Mail to user
                var emailTemplate = new EmailTemplate();
                emailTemplate.SendOpenTicket(latestTicket.TicketID, createTicketModel.Username);

                // Success message
                this.SetSuccess("De ticket is succesvol toegevoegd!");

                // Log
                LogProvider.LogAction(
                    string.Format("De ticket #{0} is toegevoegd", latestTicket.TicketID));

                // Redirect
                return RedirectToAction("Alle-tickets-weergeven");
            }
            return View(createTicketModel);
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        public ActionResult ReactieToevoegen(TicketReplyModel ticketReplyModel)
        {
            if (ModelState.IsValid)
            {
                var ticketReactieRepository = new TicketReactieRepository();
                var ticketInfo = new TicketReactie
                {
                    GebruikersId = UserProvider.GetUserId(),
                    Datum = DateTime.Now,
                    Reactie = ticketReplyModel.Bericht,
                    TicketID = ticketReplyModel.TicketId
                };

                ticketReactieRepository.Add(ticketInfo);
                ticketReactieRepository.Save();

                // Mail to user
                var emailTemplate = new EmailTemplate();
                emailTemplate.SendReactionTicket(ticketReplyModel.TicketId, UserProvider.GetUsername());

                LogProvider.LogAction(
                    string.Format("Reactie toegevoegd aan de ticket #{0}", ticketInfo.TicketID));

                this.SetSuccess("Uw reactie is toegevoegd aan de ticket.");

                if (Request.UrlReferrer != null)
                {
                    return RedirectToAction(Request.UrlReferrer.AbsoluteUri);
                }
                return RedirectToAction("alle-tickets-weergeven");
            }

            BundleTicketModel bundleTicketModel = GetTicketPageInfo(ticketReplyModel.TicketId);
            bundleTicketModel.TicketReplyModel = ticketReplyModel;

            return View(bundleTicketModel);
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        public ActionResult Actie(int ticketId, int actionId)
        {
            var ticketRepository = new TicketRepository();
            Ticket ticketInfo = ticketRepository.GetById(ticketId);

            // Sluiten
            if (actionId == 2)
            {
                ticketInfo.Status = 2;
                ticketRepository.Save();

                // Email ticket is gesloten
                var emailTemplate = new EmailTemplate();
                emailTemplate.SendClosedTicket(ticketId, UserProvider.GetUsername());

                this.SetSuccess("De ticket is succesvol gesloten!");
            }
            // Her-openen
            else
            {
                ticketInfo.Status = 0;
                ticketRepository.Save();

                // Email ticket is her-opened
                var emailTemplate = new EmailTemplate();
                emailTemplate.SendOpenTicket(ticketId, UserProvider.GetUsername());

                this.SetSuccess("De ticket is succesvol heropend!");
            }

            if (Request.UrlReferrer != null)
            {
                return Redirect(Request.UrlReferrer.AbsolutePath);
            }
            return RedirectToAction("Alle-tickets-weergeven");
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        public ActionResult _Info(int id)
        {
            return View(GetTicketPageInfo(id));
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        public ActionResult Info(int id)
        {
            return View(id);
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        [HttpPost]
        public ActionResult Info(TicketReplyModel ticketReplyModel)
        {
            if (ModelState.IsValid)
            {
                var ticketReactionRepository = new TicketReactieRepository();
                ticketReactionRepository.Add(new TicketReactie
                {
                    Datum = DateTime.Now,
                    GebruikersId = UserProvider.GetUserId(),
                    Reactie = ticketReplyModel.Bericht,
                    TicketID = ticketReplyModel.TicketId
                });

                ticketReactionRepository.Save();

                this.SetSuccess("Uw reactie is succesvol toegevoegd.");

                // Redirect
                return Redirect(Request.Url.AbsolutePath);
            }

            // Return model
            BundleTicketModel ticketInfo = GetTicketPageInfo(ticketReplyModel.TicketId);
            ticketInfo.TicketReplyModel = ticketReplyModel;

            return View(ticketInfo);
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Ticket)]
        public ActionResult Verwijder(int id)
        {
            var ticketReactionRepository = new TicketReactieRepository();
            var ticketRepository = new TicketRepository();

            Ticket ticketInfo = ticketRepository.GetById(id);

            if (ticketInfo != null)
            {
                // Send email

Areas/Admin/Views/Tickets/Shared/_Alle-Tickets-Weergeven.cshtml
@model IEnumerable<Common.Models.Admin.ViewModel.TicketModel>

@{
    Layout = null;
}
<div class="col-md-12" id="tickets">
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                   @{Html.RenderPartial("Partials/_PanelNavigation");}
                    <div class="panel-title">Alle tickets</div>
                </div>

                <div class="panel-body">
                    <div class="pull-left">
                        @Html.ActionLink("Ticket toevoegen", "Toevoegen", null, new {@class = "btn btn-default btn-gradient"})
                    </div>

                    @Html.Partial("~/Areas/Admin/Views/Tickets/Partials/PartialTicketsWeergeven.cshtml")
                </div>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Tickets/Shared/_Behandelde-Tickets-Weergeven.cshtml
@model IEnumerable<Common.Models.Admin.ViewModel.TicketModel>

@{
    Layout = null;
}
<div class="col-md-12" id="tickets">
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    @{Html.RenderPartial("Partials/_PanelNavigation");}
                    <div class="panel-title">Tickets in behandeling</div>
                </div>
                <div class="panel-body">
                    <div class="pull-left">
                        @Html.ActionLink("Ticket toevoegen", "Toevoegen", null, new {@class = "btn btn-default btn-gradient"})
                    </div>
                    @Html.Partial("~/Areas/Admin/Views/Tickets/Partials/PartialTicketsWeergeven.cshtml")
                </div>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Tickets/Shared/_Gesloten-Tickets-Weergeven.cshtml
@model IEnumerable<Common.Models.Admin.ViewModel.TicketModel>

@{
    Layout = null;
}
<div id="tickets" class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    @{Html.RenderPartial("Partials/_PanelNavigation");}
                    <div class="panel-title">Alle gesloten tickets</div>
                </div>
                <div class="panel-body">
                    <div class="pull-left">
                        @Html.ActionLink("Ticket toevoegen", "Toevoegen", null, new {@class = "btn btn-default btn-gradient"})
                    </div>
                    @Html.Partial("~/Areas/Admin/Views/Tickets/Partials/PartialTicketsWeergeven.cshtml")
                </div>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Tickets/Shared/_Info.cshtml
@{
    Layout = null;
}

@using Common.Models.Admin.Tickets
@using Common.Models.Admin.ViewModel
@using Kapsters.Areas.Admin.Controllers
@model Common.Models.Admin.ViewModel.BundleTicketModel

<div class="col-md-12">
    <div id="ticketInformatie">
        <div class="row">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="panel-title">#@Model.TicketModel.TicketID @Model.TicketModel.Onderwerp <div class="pull-right">
                                                                                                               @switch ((TicketType) Model.TicketModel.Status)
                                                                                                               {
                                                                                                                   case TicketType.Open:
                                                                                                                   {
                                                                                                                       @Html.Raw("<span class='label label-success'>Open</span>")
                                                                                                                       break;
                                                                                                                   }
                                                                                                                   case TicketType.Review:
                                                                                                                   {
                                                                                                                       @Html.Raw("<span class='label label-warning'>In behandeling</span>")
                                                                                                                       break;
                                                                                                                   }
                                                                                                                   case TicketType.Closed:
                                                                                                                   {
                                                                                                                       @Html.Raw("<span class='label label-danger'>Gesloten</span>")
                                                                                                                       break;
                                                                                                                   }
                                                                                                               }
                            
                                                                                                           </div></div>
                    </div>
                    <div class="panel-body">
                        @{ var counter = 0; }
                        @foreach (TicketReactiesModel reactie in Model.TicketReactieModel)
                        {
                            <div class="well @if (reactie.isAdministratief)
                                             {
                                                 @Html.Raw("gebruiker")
                                             } @if (Model.TicketReactieModel.Count - counter == 1)
                                               {
                                                   @Html.Raw("noMargin")
                                               }">
                                <div class="media-content">
                                    <h4 class="media-heading">@reactie.Voornaam @reactie.Achternaam</h4>
                                    <p>@(reactie.isAdministratief ? @Html.Raw("<label class='label label-warning'> " + reactie.GebruikersGroepNaam + "</label> ") : @Html.Raw("<label class='label label-info'> " + reactie.GebruikersGroepNaam + "</label>"))</p>
                                    <p class="media-timestamp">@string.Format("{0:d-MM-yyyy HH:mm}", reactie.Datum)</p>
                                
                                    <hr/>
                                    @Html.Raw(reactie.Bericht)
                                </div>
                            </div>
                            counter++;
                        }
                        
                        @if (Model.TicketModel.Status != 2)
                        {
                            <div class="panel space" id="reactieToevoegen">
                                <div class="panel-heading">Reactie toevoegen</div>
                                <div class="panel-body">
                                    @using (Html.BeginForm())
                                    {
                                        @Html.HiddenFor(m => m.TicketReplyModel.TicketId)
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.TicketReplyModel.Bericht)
                                            @Html.TextAreaFor(m => m.TicketReplyModel.Bericht, new {@class = "form-control", rows = "5"})
                                            @Html.ValidationMessageFor(m => m.TicketReplyModel.Bericht)
                                        </div>
                                        <input type="submit" value="Reactie toevoegen!" class="btn btn-primary btn-gradient"/>
                                    }
                                </div>
                            </div>
                        }
                      
                        <div id="action">
                            @if (Model.TicketModel.Status != 2)
                            {
                                @Html.ActionLink("Sluiten", "Actie", "Tickets", new {@ticketId = Model.TicketModel.TicketID, @actionId = "2"}, new {@class = "btn btn-danger btn-gradient pull-right"})
                            }
                            else if (Model.TicketModel.Status == 2)
                            {
                                @Html.ActionLink("Her-openen", "Actie", "Tickets", new {@ticketId = Model.TicketModel.TicketID, @actionId = "0"}, new {@class = "btn btn-info btn-gradient pull-right"})
                            }
                        </div>
                    </div>

                    <div class="panel-footer"></div>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Tickets/Shared/_Open-Tickets-Weergeven.cshtml
@model IEnumerable<Common.Models.Admin.ViewModel.TicketModel>

@{
    Layout = null;
}
<div id="tickets" class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    @{Html.RenderPartial("Partials/_PanelNavigation");}
                    <div class="panel-title">Open tickets</div>
                </div>
                <div class="panel-body">
                    <div class="pull-left">
                        @Html.ActionLink("Ticket toevoegen", "Toevoegen", null, new {@class = "btn btn-default btn-gradient"})
                    </div>
                    @Html.Partial("~/Areas/Admin/Views/Tickets/Partials/PartialTicketsWeergeven.cshtml")
                </div>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>