Areas/Admin/Controllers/NieuwsController.cs
#region

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using Common.Models.Admin.ViewModel;
using Common.Providers.Files;
using Common.Providers.Logging;
using Common.Providers.Messages;
using Common.Providers.Roles;
using Common.Providers.Users;
using Common.Repositories;

#endregion

namespace Kapsters.Areas.Admin.Controllers
{
    public class NieuwsController : ApplicationController
    {
        private NieuwsRepository NewsRepository { get; set; }
        private NewsCommentsRepository NewsCommentsRepository { get; set; }

        public NieuwsController()
        {
            NewsRepository = new NieuwsRepository();
            NewsCommentsRepository = new NewsCommentsRepository();
        }

        //[OutputCache(SqlDependency = "Pubs:NieuwsArtikel", Duration = 600)]
        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        public ActionResult _Weergeven()
        {
            var blogsList = NewsRepository.GetList();

            var modelNewsList = blogsList.Select(artikel => new NieuwsModel
            {
                ArtikelId = artikel.ArtikelID,
                AantalReacties = artikel.NieuwsReacties.Count,
                AuteurNaam = UserProvider.GetFullName(artikel.AuteurId),
                Datum = artikel.Datum,
                Informatie = artikel.Informatie,
                ReactiesToegestaan = artikel.ReactiesToegestaan,
                Titel = artikel.Titel,
                Status = artikel.Status,
                Keywoorden = artikel.Keywords
            }).ToList();

            return View(modelNewsList);
        }

        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        public ActionResult Weergeven()
        {
            return View();
        }

        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        public ActionResult Wijzig(int id)
        {
            Nieuwsartikel nieuwsInfo = NewsRepository.GetById(id);

            var nieuwsModel = new NieuwsModel
            {
                Titel = nieuwsInfo.Titel,
                Informatie = nieuwsInfo.Informatie,
                ArtikelId = nieuwsInfo.ArtikelID,
                Status = nieuwsInfo.Status,
                ReactiesToegestaan = nieuwsInfo.ReactiesToegestaan,
                Keywoorden = nieuwsInfo.Keywords,
                Intro = nieuwsInfo.Intro
            };

            return View(nieuwsModel);
        }

        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        public ActionResult Verwijder(int id)
        {
            Nieuwsartikel nieuwsInfo = NewsRepository.GetById(id);

            if (nieuwsInfo != null)
            {
                NewsRepository.Remove(nieuwsInfo);
                NewsRepository.Save();
                LogProvider.LogAction(
                    string.Format("De nieuwsartikel #{0} is verwijderd", nieuwsInfo.ArtikelID));
                this.SetSuccess("Het nieuwsartikel is succesvol verwijderd.");
            }
            else
            {
                this.SetError("Het nieuwsartikel is niet verwijderd want hij bestaat niet.");
            }

            return RedirectToAction("Weergeven");
        }

        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        [HttpPost]
        public ActionResult Wijzig(NieuwsModel nieuwsModel)
        {
            if (ModelState.IsValid)
            {
                Nieuwsartikel nieuwsInfo = NewsRepository.GetById(nieuwsModel.ArtikelId);

                nieuwsInfo.Titel = nieuwsModel.Titel;
                nieuwsInfo.Informatie = nieuwsModel.Informatie;
                nieuwsInfo.Status = nieuwsModel.Status;
                nieuwsInfo.ReactiesToegestaan = nieuwsModel.ReactiesToegestaan;
                nieuwsInfo.Keywords = nieuwsModel.Keywoorden;
                nieuwsInfo.Intro = nieuwsModel.Intro;

                NewsRepository.Save();

                EditImage(nieuwsInfo.ArtikelID, nieuwsModel.UploadImage);

                LogProvider.LogAction(
                    string.Format("Het nieuwsartikel #{0} is gewijzigd", nieuwsInfo.ArtikelID));

                this.SetSuccess("Het nieuwsartikel is succesvol gewijzigd.");

                return RedirectToAction("Weergeven");
            }

            this.SetError("Het nieuwsartikel is niet gewijzigd, controleer uw velden.");

            return View(nieuwsModel);
        }

        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        [HttpPost]
        public ActionResult Toevoegen(NieuwsModel nieuwsModel)
        {
            if (ModelState.IsValid)
            {
                var newsTable = new Nieuwsartikel
                {
                    AuteurId = UserProvider.GetUserId(),
                    Datum = DateTime.Now,
                    Informatie = nieuwsModel.Informatie,
                    Titel = nieuwsModel.Titel,
                    ReactiesToegestaan = nieuwsModel.ReactiesToegestaan,
                    Status = nieuwsModel.Status,
                    Keywords = nieuwsModel.Keywoorden,
                    Intro = nieuwsModel.Intro,
                    Image = FileProvider.GetNewImageName(nieuwsModel.UploadImage)
                };

                NewsRepository.Add(newsTable);
                NewsRepository.Save();

                AddImage(nieuwsModel.UploadImage, newsTable.ArtikelID);

                // Get news info
                var newsInfo = NewsRepository.GetLastAdded();

                LogProvider.LogAction(
                    string.Format("Het nieuwsartikel #{0} is toegevoegd", newsInfo.ArtikelID));

                this.SetSuccess("Het artikel is succesvol toegevoegd.");

                return RedirectToAction("Weergeven");
            }
            return View(nieuwsModel);
        }

        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        public ActionResult Toevoegen()
        {
            return View(new NieuwsModel
            {
                Status = true,
                ReactiesToegestaan = true
            });
        }

        [HttpGet]
        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        [ActionName("Reactie-Wijzigen")]
        public ActionResult WijzigReactie(int id)
        {
            NieuwsReactie newsReactionInfo = NewsCommentsRepository.GetById(id);

            var model = new EditNewsReactionModel
            {
                Message = newsReactionInfo.Bericht,
                ReactionId = newsReactionInfo.ReactieID,
                Status = newsReactionInfo.Status
            };

            return View(model);
        }

        [HttpPost]
        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        [ActionName("Reactie-Wijzigen")]
        public ActionResult WijzigReactie(EditNewsReactionModel editNewsReactionModel)
        {
            if (ModelState.IsValid)
            {
                NieuwsReactie newsReactionInfo = NewsCommentsRepository.GetById(editNewsReactionModel.ReactionId);

                newsReactionInfo.Bericht = editNewsReactionModel.Message;
                newsReactionInfo.Status = editNewsReactionModel.Status;

                NewsCommentsRepository.Save();

                LogProvider.LogAction(
                    string.Format("De nieuwsreactie #{0} is gewijzigd", newsReactionInfo.ReactieID));

                this.SetSuccess("De nieuwsreactie is succesvol gewijzigd");

                return RedirectToAction("Reacties-Weergeven", new { id = editNewsReactionModel.ReactionId });
            }
            return View(editNewsReactionModel);
        }


        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        public ActionResult VerwijderReactie(int id)
        {
            NieuwsReactie reactionInfo = NewsCommentsRepository.GetById(id);

            if (reactionInfo != null)
            {
                NewsCommentsRepository.Remove(reactionInfo);
                NewsCommentsRepository.Save();

                LogProvider.LogAction(
                    string.Format("De nieuwsreactie #{0} is verwijderd", reactionInfo.ReactieID));

                this.SetSuccess("De nieuws reactie is succesvol verwijderd.");
            }
            else
            {
                this.SetError("De nieuws reactie is niet verwijderd want hij bestaat niet.");
            }

            return RedirectToAction("Reacties-Weergeven");
        }

        [ActionName("_Reacties-Weergeven")]
        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        public ActionResult _ReactiesWeergeven(int id)
        {
            var listReactionsTable = NewsCommentsRepository.GetListByArticleId(id);

            var listModels = listReactionsTable.Select(row => new NewsReactionsModel
            {
                Name = row.ReactieGebruikersId == null ? row.Name : UserProvider.GetFullName((Guid)row.ReactieGebruikersId),
                ReactionId = row.ReactieID,
                Status = row.Status,
                Date = row.Datum
            }).ToList();

            return View(listModels);
        }

        [ActionName("Reacties-Weergeven")]
        [RolePermission(permissionName = RolePermission.PermissionName.News)]
        public ActionResult ReactiesWeergeven(int id)
        {
            return View(id);
        }

        #region Private Methods

        private void AddImage(HttpPostedFileBase postedFile, int newsArticleId)
        {
            // Check if we uploaded a file
            if (postedFile != null)
            {
                // Add folder
                FileProvider.AddFolderDirectory(FilePaths.Blogs, newsArticleId.ToString(CultureInfo.InvariantCulture), false);

                // Add image

Areas/Admin/Views/Nieuws/Reactie-Wijzigen.cshtml
@model Common.Models.Admin.ViewModel.EditNewsReactionModel

@{
    ViewBag.Title = "Nieuws reactie wijzigen";
}
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <div class="panel-title">Nieuws reactie wijzigen</div>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm())
                    {
                        @Html.HiddenFor(m => m.ReactionId)

                        <div class="form-group">
                            @Html.LabelFor(m => m.Message)
                            @Html.TextAreaFor(m => m.Message, new {@class = "form-control"})
                            @Html.ValidationMessageFor(m => m.Message)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Status)
                        @Html.CheckBoxFor(m => m.Status, new { @class = "make-switch", @checked = "checked" })
                            @Html.ValidationMessageFor(m => m.Status)
                        </div>

                        <input type="submit" value="Reactie wijzigen!" class="btn btn-info btn-gradient"/>
                    }
                </div>

                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>

@section Styles{
    <link rel="stylesheet" href="@Url.Content("~/Areas/Admin/Content/css/bootstrap-switch-min.css")" />
}

@section Scripts{
    @Scripts.Render("~/Areas/Admin/Content/tinymce")
    <script src="@Url.Content("~/Areas/Admin/Content/js/bootstrap-switch-min.js")"></script>
    <script>
        tinyMCE.baseURL = "/Areas/Admin/Content/js/tinymce/";
        tinymce.init({
            selector: "textarea",
            language: 'nl',
            plugins: 'advlist autolink link image lists charmap print preview fullscreen table textcolor code paste template visualchars visualblocks'
        });
    </script>
}

Areas/Admin/Views/Nieuws/Reacties-Weergeven.cshtml
@model int

<div id="viewContent" data-url="@Url.Action("_Reacties-Weergeven", "Nieuws", new {@id = Model})"></div>


@section Scripts{
    @Scripts.Render("~/Areas/Admin/Content/js/datatables")

    <script>
        $(function () {
            $('#datatable').footable();
        });
    </script>
}

@section Styles{
    @Styles.Render("~/Areas/Admin/Content/css/datatables")
}

Areas/Admin/Views/Nieuws/Toevoegen.cshtml
@using Glimpse.Core.Configuration
@model Common.Models.Admin.ViewModel.NieuwsModel

@{
    ViewBag.Title = "Nieuwsartikel toevoegen";
}
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <div class="panel-title">Nieuwsartikel toevoegen</div>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("Toevoegen", "Nieuws", FormMethod.Post, new {enctype = "multipart/form-data", id = "form"}))
                    {
                        <div class="form-group">
                            @Html.LabelFor(m => m.Titel)
                            @Html.TextBoxFor(m => m.Titel, new {@class = "form-control"})
                            @Html.ValidationMessageFor(m => m.Titel)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Intro)
                            @Html.TextAreaFor(m => m.Intro, new {@class = "form-control"})
                            @Html.ValidationMessageFor(m => m.Intro)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Informatie)
                            @Html.TextAreaFor(m => m.Informatie, new {@class = "form-control Informatie"})
                            @Html.ValidationMessageFor(m => m.Informatie)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Keywoorden)
                            @Html.TextBoxFor(m => m.Keywoorden, new {@class = "form-control"})
                            @Html.ValidationMessageFor(m => m.Keywoorden)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.UploadImage)
                            @Html.TextBoxFor(m => m.UploadImage, new {@type = "file"})
                            @Html.ValidationMessageFor(m => m.UploadImage)
                        </div>

                        <div class="form-group">
                            <div class="fullWidth">
                                <span class="info-icon tool-tip" data-toggle="tooltip" data-placement="right" title="Is dit artikel zichtbaar?"></span>
                                @Html.LabelFor(m => m.Status, new {@class = "tooltip-label"})
                            </div>
                          @Html.CheckBoxFor(m => m.Status, new { @class = "make-switch", @checked = "checked" })
                            @Html.ValidationMessageFor(m => m.Status)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.ReactiesToegestaan)

                            @Html.CheckBoxFor(m => m.ReactiesToegestaan, new { @class = "make-switch", @checked = "checked" })

                        </div>

                        <input type="submit" value="Artikel toevoegen!" class="btn btn-info btn-gradient" />
                    }
                </div>

                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>

@section Styles{
    <link rel="stylesheet" href="@Url.Content("~/Areas/Admin/Content/css/bootstrap-switch-min.css")" />
}

@section Scripts{
    <script src="@Url.Content("~/Areas/Admin/Content/js/fileButtonReplacer.js")"></script>
    <script src="@Url.Content("~/Areas/Admin/Content/js/bootstrap-switch-min.js")"></script>
    @Scripts.Render("~/Areas/Admin/Content/tinymce")

    <script>
        tinyMCE.baseURL = "/Areas/Admin/Content/js/tinymce/";
        tinymce.init({
            mode: "specific_textareas",
            editor_selector: "Informatie",
            language: 'nl',
            plugins: 'advlist autolink link image lists charmap print preview fullscreen table textcolor code paste template visualchars visualblocks'
        });
    </script>
}

Areas/Admin/Views/Nieuws/Weergeven.cshtml
<div id="viewContent" data-url="@Url.Action("_Weergeven", "Nieuws")"></div>


@section Scripts{
    @Scripts.Render("~/Areas/Admin/Content/js/datatables")

    <script>
        $(function () {
            $('#datatable').footable();
        });
    </script>
}

@section Styles{
    @Styles.Render("~/Areas/Admin/Content/css/datatables")
}

Areas/Admin/Views/Nieuws/Wijzig.cshtml
@model Common.Models.Admin.ViewModel.NieuwsModel

@{
    ViewBag.Title = "Nieuwsartikel wijzigen";
}
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <div class="panel-title">Artikel wijzigen</div>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("Wijzig", "Nieuws", FormMethod.Post, new {enctype = "multipart/form-data", id = "form"}))
                    {
                        @Html.HiddenFor(m => m.ArtikelId)

                        <div class="form-group">
                            @Html.LabelFor(m => m.Titel)
                            @Html.TextBoxFor(m => m.Titel, new {@class = "form-control"})
                            @Html.ValidationMessageFor(m => m.Titel)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Intro)
                            @Html.TextAreaFor(m => m.Intro, new {@class = "form-control"})
                            @Html.ValidationMessageFor(m => m.Intro)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Informatie)
                            @Html.TextAreaFor(m => m.Informatie, new {@class = "form-control tinymce"})
                            @Html.ValidationMessageFor(m => m.Informatie)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Keywoorden)
                            @Html.TextBoxFor(m => m.Keywoorden, new {@class = "form-control"})
                            @Html.ValidationMessageFor(m => m.Keywoorden)
                        </div>

                        <div class="form-group">
                            <div class="fullWidth">
                                <span class="info-icon tool-tip" data-toggle="tooltip" data-placement="right" title="Als u nu een nieuwe afbeelding kiest dan wordt uw vorige afbeelding overschreven"></span>
                                @Html.LabelFor(m => m.UploadImage, new {@class = "tooltip-label"})
                            </div>
                            @Html.TextBoxFor(m => m.UploadImage, new {@type = "file"})
                            @Html.ValidationMessageFor(m => m.UploadImage)
                        </div>

                        <div class="form-group">
                            <div class="fullWidth">
                                <span class="info-icon tool-tip" data-toggle="tooltip" data-placement="right" title="Is dit artikel zichtbaar?"></span>
                                @Html.LabelFor(m => m.Status, new {@class = "tooltip-label"})
                            </div>
                        @Html.CheckBoxFor(m => m.Status, new { @class = "make-switch", @checked = "checked" })
                            @Html.ValidationMessageFor(m => m.Status)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.ReactiesToegestaan)
                           @Html.CheckBoxFor(m => m.ReactiesToegestaan, new { @class = "make-switch", @checked = "checked" })
                        </div>

                        <input type="submit" value="Artikel wijzigen!" class="btn btn-info btn-gradient" />
                    }
                </div>

                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>

@section Styles{
    <link rel="stylesheet" href="@Url.Content("~/Areas/Admin/Content/css/bootstrap-switch-min.css")" />
}

@section Scripts{
    <script src="@Url.Content("~/Areas/Admin/Content/js/bootstrap-switch-min.js")"></script>
    @Scripts.Render("~/Areas/Admin/Content/js/datatables")
    <script src="@Url.Content("~/Areas/Admin/Content/js/fileButtonReplacer.js")"></script>

    <script>
        tinyMCE.baseURL = "/Areas/Admin/Content/js/tinymce/";
        tinymce.init({
            mode: "specific_textareas",
            editor_selector: "tinymce",
            language: 'nl',
            plugins: 'advlist autolink link image lists charmap print preview fullscreen table textcolor code paste template visualchars visualblocks'
        });

    </script>
}