Areas/Admin/Controllers/DashboardController.cs
#region

using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI;
using Common;
using Common.Models.Admin.Dashboard;
using Common.Models.Admin.Tickets;
using Common.Models.Admin.Users;
using Common.Models.Admin.ViewModel;
using Common.Providers.Caching;
using Common.Providers.Date;
using Common.Providers.Email;
using Common.Providers.Roles;
using Common.Providers.Users;
using Common.Repositories;
using DevTrends.MvcDonutCaching;
using Kapsters.Areas.Admin.Tasks;
using AdminNavigation = Kapsters.Areas.Admin.Functionality.Navigation.AdminNavigation;
using HttpContext = System.Web.HttpContext;
using Membership = System.Web.Security.Membership;

#endregion

namespace Kapsters.Areas.Admin.Controllers
{
    public class DashboardController : ApplicationController
    {

        public ActionResult _Index()
        {
            var bundleModel = new BundleDashboardModel();

            AddTickets(ref bundleModel);

            AddBlog(ref bundleModel);

            AddGuestbook(ref bundleModel);

            AddNews(ref bundleModel);

            AddUsers(ref bundleModel);

            SetPermissionsAgenda(ref bundleModel);

            return View(bundleModel);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Contact(ContactDashboardModel contactDashboardModel)
        {
            if (ModelState.IsValid)
            {
                var email = new Email();
                email.SendEmail("info@jamieknoef.nl", "Contactformulier CMS - " + contactDashboardModel.Subject,
                    contactDashboardModel.Message, true);
            }
            return RedirectToAction("Index");
        }

        #region Index Functions

        private void AddTickets(ref BundleDashboardModel bundleModel)
        {
            var rightRepository = new RightRepository();

            var ticketRight = rightRepository.GetById(11);

            // Get tickets
            if (ticketRight.Status && RoleProvider.HasRight(11, RoleProvider.GetRoleId()))
            {
                bundleModel.TicketsReactions = GetTicketsReactions();
                bundleModel.HasTicketPermission = true;
            }
        }

        private void AddBlog(ref BundleDashboardModel bundleModel)
        {
            var rightRepository = new RightRepository();

            // Get blog
            var blogRight = rightRepository.GetById(1);

            if (blogRight.Status && RoleProvider.HasRight(1, RoleProvider.GetRoleId()))
            {
                bundleModel.BlogReactions = GetBlogReactions();
                bundleModel.HasBlogPermission = true;
            }
        }

        private void AddGuestbook(ref BundleDashboardModel bundleModel)
        {
            var rightRepository = new RightRepository();

            // Get guestbook
            var guestbookRight = rightRepository.GetById(13);

            if (guestbookRight.Status && RoleProvider.HasRight(13, RoleProvider.GetRoleId()))
            {
                bundleModel.HasGuestbookPermission = true;
                bundleModel.GuestbookReactions = GetGuestbookReactions();
            }
        }

        private void AddNews(ref BundleDashboardModel bundleModel)
        {
            var rightRepository = new RightRepository();

            // Get news
            var newsRight = rightRepository.GetById(9);

            if (newsRight.Status && RoleProvider.HasRight(9, RoleProvider.GetRoleId()))
            {
                bundleModel.NewsReactions = GetNewsReactions();
                bundleModel.HasNewsPermission = true;

                var newsRepository = new NieuwsRepository();

                // Load news
                List<Nieuwsartikel> listTableNews =
                    newsRepository.GetList().Take(5).OrderByDescending(x => x.ArtikelID).ToList();

                foreach (Nieuwsartikel tableNews in listTableNews)
                {
                    bundleModel.NewsModels.Add(new NieuwsModel
                    {
                        AuteurNaam = UserProvider.GetFullName(tableNews.AuteurId),
                        Informatie = tableNews.Informatie,
                        AantalReacties = tableNews.NieuwsReacties.Count,
                        Titel = tableNews.Titel,
                        ArtikelId = tableNews.ArtikelID,
                        Datum = tableNews.Datum
                    });
                }

            }
        }

        private void AddUsers(ref BundleDashboardModel bundleModel)
        {
            var rightRepository = new RightRepository();

            // Get users
            var usersRight = rightRepository.GetById(5);

            if (usersRight.Status && RoleProvider.HasRight(6, RoleProvider.GetRoleId()))
            {
                bundleModel.UsersAwaiting = GetAmountUsers();

                // Load users
                bundleModel.UsersModels = UserProvider.GetAllUsers(5).OrderByDescending(x => x.CreatedDate).ToList();

                bundleModel.HasUsersPermission = true;
            }
        }

        private void SetPermissionsAgenda(ref BundleDashboardModel bundleModel)
        {
            var rightRepository = new RightRepository();

            // Get users
            var agendaRight = rightRepository.GetById(17);

            if (agendaRight.Status && RoleProvider.HasRight(6, RoleProvider.GetRoleId()))
            {
                bundleModel.HasAgendaPermission = true;
            }
        }

        private int GetBlogReactions()
        {
            var blogReactionsRepository = new BlogReactionRepository();
            return blogReactionsRepository.GetAmountOpenComments();
        }

        private int GetNewsReactions()
        {
            var newsReactionsRepository = new NewsCommentsRepository();
            return newsReactionsRepository.GetAmountOpenComments();
        }

        private int GetGuestbookReactions()
        {
            var guestbookReactionsRepository = new GastenboekRepository();
            return guestbookReactionsRepository.GetAmountOpenComments();
        }

        private int GetTicketsReactions()
        {
            var ticketsRepository = new TicketRepository();
            return ticketsRepository.GetAmountOpenTickets();
        }

        private int GetAmountUsers()
        {
            var membershipRepository = new MembershipRepository();
            return membershipRepository.GetUnverifiedUsers();
        }
        #endregion

        #region Public Ajax Methods

        public JsonResult GetStatistics()
        {
            return Json(CreateStatistics(), JsonRequestBehavior.AllowGet);
        }

        public async Task<string> GetJamieKnoefNews()
        {
            string downloadedContent = string.Empty;

            return await Task<string>.Factory.StartNew(() =>
            {
                try
                {
                    WebRequest request = WebRequest.Create("http://jamieknoef.nl/CMSNews.html");
                    WebResponse response = request.GetResponse();
                    Stream data = response.GetResponseStream();

                    if (data != null)
                    {
                        using (var sr = new StreamReader(data))
                        {
                            downloadedContent = sr.ReadToEnd();
                        }
                    }
                }
                catch
                {
                    return null;
                }
                

                return downloadedContent;
            });
        }

        private IEnumerable<StatisticsDashboardModel> CreateStatistics()
        {
            var dashboardStatisticsRepository = new DashboardStatisticsRepository();
            var returnListStatistics = new Collection<StatisticsDashboardModel>();

            IQueryable<StatsVisit> listStatistics = dashboardStatisticsRepository.GetStatisticsLast7Days();

            foreach (StatsVisit statistic in listStatistics)
            {
                returnListStatistics.Add(new StatisticsDashboardModel
                {
                    Pageviews = statistic.Pageviews,
                    Visitors = statistic.Visitors,
                    Date = string.Format("{0:d MMMM}", statistic.Date)
                });
            }

            return returnListStatistics;
        }

        public void UpdateActionLog()
        {
            var userActionLogRepository = new UserActionLogRepository();
            var actionLogRepository = new ActionLogRepository();

            var userActionLogInfo = userActionLogRepository.GetFirst(UserProvider.GetUserId());
            userActionLogInfo.ActionLogId = actionLogRepository.GetHighestActionId();

            userActionLogRepository.Save();

            //     var cacheManager = new OutputCacheManager();
            //      cacheManager.RemoveItem("Dashboard", "GetActionLogs");
        }

        #endregion

        #region Topbar Actions


        [ChildActionOnly]
        //[DonutOutputCache(Duration = 900, VaryByParam = "none", VaryByCustom = "username",Location = OutputCacheLocation.Server)]
        public ActionResult GetActionLogs()
        {
            var actionLogRepository = new ActionLogRepository();

            var actionLogModel = new ActionLogModel
            {
                AmountNewActionLogs = actionLogRepository.GetAmountNewActionLogs(),
                ActionLogModels = actionLogRepository.GetNewActionLogs()
            };

            return PartialView("GetActionLogs", actionLogModel);
        }

        [ChildActionOnly]
        // [DonutOutputCache(Duration = 900, VaryByParam = "none", VaryByCustom = "username", Location = OutputCacheLocation.Server)]
        public ActionResult GetUsers()
        {
            // Get latest users

Areas/Admin/Controllers/LogsController.cs
#region

using System.Collections.ObjectModel;
using System.Web.Mvc;
using Common.Models.Admin.Logs;
using Common.Providers.Logging;
using Common.Providers.Messages;
using Common.Providers.Roles;
using Common.Repositories;

#endregion

namespace Kapsters.Areas.Admin.Controllers
{
    public class LogsController : ApplicationController
    {

        //
        // GET: /Logs/

        [RolePermission(permissionName = RolePermission.PermissionName.Log)]
        public ActionResult Foutmeldingen()
        {
            //var errorLogRepository = new ErrorLogRepository();
            //return View(errorLogRepository.GetList());
            return View();
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Log)]
        public ActionResult ShowError(int id)
        {
            var errorLogRepository = new ErrorLogRepository();
            var errorLogInfo = errorLogRepository.GetById(id);
            return View(errorLogInfo);
        }

        public ActionResult Activiteiten()
        {
            return View();
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Log)]
        public ActionResult _Activiteiten()
        {
            var actionLogRepository = new ActionLogRepository();
            var listActivities = actionLogRepository.GetList();

            var userRepository = new GebruikersRepository();

            var listModel = new Collection<ActivitiesModel>();

            foreach (var activity in listActivities)
            {
                var userInfo = userRepository.GetById(activity.UserId);

                listModel.Add(new ActivitiesModel
                {
                    Action = activity.Action,
                    Controller = activity.Controller,
                    Date = activity.Date,
                    Fullname = userInfo.Voornaam + " " + userInfo.Achternaam,
                    Information = activity.Information
                });
            }
            return View(listModel);
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Log)]
        public ActionResult VerwijderErrors()
        {
            var errorLogRepository = new ErrorLogRepository();
            errorLogRepository.RemoveAll();
            errorLogRepository.Save();

            LogProvider.LogAction(
                string.Format("Het error logboek is geleegd"));

            this.SetSuccess("Het error logboek is geleegd.");

            return RedirectToAction("Error");
        }

        [RolePermission(permissionName = RolePermission.PermissionName.Log)]
        public ActionResult VerwijderActiviteiten()
        {
            var actionLogRepository = new ActionLogRepository();
            actionLogRepository.RemoveAll();
            actionLogRepository.Save();

            LogProvider.LogAction(
                string.Format("Het activiteiten logboek is geleegd"));

            this.SetSuccess("De activiteiten logboek is geleegd.");

            return RedirectToAction("Activiteiten");
        }
    }
}

Areas/Admin/Views/Dashboard/GetActionLogs.cshtml
@model Common.Models.Admin.ViewModel.ActionLogModel

<div class="messages-menu" id="actionLog">
    <button type="button" class="btn btn-sm dropdown-animate" data-toggle="dropdown"> <span class="glyphicon glyphicon-comment"></span> <b>@Model.AmountNewActionLogs</b> </button>
    <ul class="dropdown-menu checkbox-persist" role="menu">
        <li class="menu-arrow">
            <div class="menu-arrow-up"></div>
        </li>
        <li class="dropdown-header">Recente aanpassingen <span class="pull-right glyphicons glyphicons-comments"></span></li>
        <li id="actionItems">
            <ul class="dropdown-items">
                    @foreach (var action in Model.ActionLogModels)
                     {
                         <li>
                             <div class="item-avatar"><img src="@Url.Content("/Areas/Admin/Content/img/avatars/header/2.jpg")" class="img-responsive" alt="avatar" /></div>
                             <div class="item-message">
                                 <b>@action.FullName</b> - <small class="text-muted">@action.TimeAgo</small><br />
                                 @action.Information
                             </div>
                         </li>
                     }
            </ul>
        </li>
        <li class="dropdown-footer"><a href="@Url.Action("Activiteiten", "Logs")">Weergeef alle activiteiten <i class="fa fa-caret-right"></i> </a></li>
    </ul>
</div>

Areas/Admin/Views/Dashboard/GetTickets.cshtml
@model Common.Models.Admin.Tickets.NewTicketModel

@if (Model.Status)
{
    <div class="tasks-menu">
        <button type="button" class="btn btn-sm" data-toggle="dropdown"> <span class="glyphicons glyphicons-tag"></span> <b>@Model.AmountNewTickets</b> </button>
        <ul class="dropdown-menu" role="menu">
            <li class="menu-arrow">
                <div class="menu-arrow-up"></div>
            </li>
            <li class="dropdown-header">Nieuwe tickets <span class="pull-right glyphicons glyphicons-comments"></span></li>
            <li>
                <ul class="dropdown-items">
                    @if (Model.AmountNewTickets > 0)
                    {
                        foreach (var ticket in Model.TicketModels)
                        {
                            <li>
                                <a href="@Url.Action("Info", "Tickets", new {@id = ticket.TicketID})">
                                    <div class="item-message">
                                        <b>@ticket.Voornaam @ticket.Achternaam</b> - <small class="text-muted">@ticket.TimeAgo</small><br />
                                        Onderwerp: @ticket.Onderwerp
                                    </div>
                                </a>
                            </li>
                        }
                    }
                    else
                    {
                        <li>Er zijn geen open tickets!</li>
                    }
                </ul>
            </li>
            <li class="dropdown-footer"><a href="@Url.Action("Alle-tickets-weergeven", "Tickets")">Weergeef alle open tickets <i class="fa fa-caret-right"></i> </a></li>
        </ul>
    </div>
}

Areas/Admin/Views/Dashboard/GetUsers.cshtml
@model Common.Models.Admin.ViewModel.NotApprovedUsersModel

<div class="alerts-menu">
    <button type="button" class="btn btn-sm" data-toggle="dropdown"><span class="glyphicons glyphicons-user"></span> <b>@Model.AmountNotApprovedUsers</b> </button>
    <ul class="dropdown-menu" role="menu">
        <li class="menu-arrow">
            <div class="menu-arrow-up"></div>
        </li>
        <li class="dropdown-header">Ongeaccepteerde gebruikers <span class="pull-right glyphicons glyphicons-comments"></span></li>
        <li>
            <ul class="dropdown-items">
                @if (Model.AmountNotApprovedUsers > 0)
                {
                    foreach (var user in Model.Users)
                    {
                        <li>
                            <div class="item-avatar"><img src="@Url.Content("/Areas/Admin/Content/img/avatars/header/2.jpg")" class="img-responsive" alt="avatar" /></div>
                            <div class="item-message">
                                <b>@user.FullName</b> - <small class="text-muted">@user.DateRegistration</small><br />
                                Wilt zich graag aanmelden voor de website.
                            </div>
                        </li>
                    }
                }
                else
                {
                    <li>Er zijn geen ongeaccepteerde gebruikers!</li>
                }
            </ul>
        </li>
        <li class="dropdown-footer"><a href="@Url.Action("Weergeven", "Gebruikers")">Weergeef alle gebruikers <i class="fa fa-caret-right"></i> </a></li>
    </ul>
</div>

Areas/Admin/Views/Dashboard/Index.cshtml
@if (!string.IsNullOrEmpty(Request.QueryString["Error"]))
{
    <div class="col-md-12">
        <div class="alert alert-danger">
            <h1>Error..</h1>
            <p>
                @Request.QueryString["Error"]
            </p>
        </div>
    </div>
}


<div id="dashboard">
    <div id="viewContent" data-url="@Url.Action("_Index")"></div>
</div>

@section Styles{
    <link type="text/css" href="@Url.Content("~/Areas/Admin/Content/css/calendar.css")" rel="stylesheet" />
}


@section Scripts{

    <script type="text/javascript" src="https:/www.google.com/jsapi"></script>
    <script type="text/javascript" src="@Url.Content("~/Areas/Admin/Content/js/calendar-min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Areas/Admin/Content/js/showAgenda.js")"></script>

    <script type="text/javascript">

        google.load("visualization", "1", { packages: ["corechart"] });


        function drawChart() {

            $.get('/Dashboard/GetStatistics', {},
                function(data) {
                    var tdata = new google.visualization.DataTable();

                    tdata.addColumn('string', 'Datum');
                    tdata.addColumn('number', 'Hits');
                    tdata.addColumn('number', 'Bezoekers');

                    for (var i = 0; i < data.length; i++) {
                        tdata.addRow([data[i].Date, data[i].Pageviews, data[i].Visitors]);
                    }

                    var options = {
                        'width': '100%',
                        'height': '300',
                        'chartArea': { 'width': '90%', 'height': '200' },
                        'legend': 'bottom',
                    };

                    // Hide loading
                    $('#dashboard #loadingStatistics').fadeOut('fast', function() {
                        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
                        chart.draw(tdata, options);
                    });
                });
        }

        $(document).ready(function() {

            // Subscribe to the ajax loaded event
            $(document).on("AjaxLoadingComplete", drawChart);

            $(window).resize(drawChart);

            // Subscribe to ajax loaded event - Get external news
            $(document).on("AjaxLoadingComplete", getExternalNews);

            // Subscribe to ajax loaded event - Get agenda
            $(document).on("AjaxLoadingComplete", window.initAgenda);

            // Get external news
            function getExternalNews() {
                $.get('/Admin/Dashboard/GetJamieKnoefNews', function (data) {
                    $('#LoadExternalNews').html(data);
                }).fail(function () {
                    alert("Het is niet gelukt om het nieuws op te halen..");
                });
            }

        });

        // Contact
        $('#sendContact').submit(function(e) {
            if ($(this).valid()) {
                $('#sendContact input[type="submit"]').button('loading');

                var ajaxCall = $.ajax({
                    url: '/Dashboard/Contact',
                    type: 'POST',
                    data: $(this).serialize()
                });

                ajaxCall.always(function() {
                    $('#dashboardContact input[type="text"]').text('');
                    $('#dashboardContact textarea').text('');
                    $('#sendContact input[type="submit"]').button('reset');
                });

                ajaxCall.success(function() {
                    $('#contactMessage').slideDown('fast');
                });

                ajaxCall.error(function() {
                    alert('Het is niet gelukt om het contactformulier te verzenden!');
                });

            }

            e.preventDefault();
        });
    </script>

    <script src="@Url.Content("~/Areas/Admin/Content/js/showAgenda.js")"></script>
}

Areas/Admin/Views/Dashboard/Navigation.cshtml
@model IEnumerable<Common.Models.Admin.Navigation.AdminNavigationModel>

<div id="sidebar-menu">
    <ul class="nav sidebar-nav">
        @foreach (var parentNavigation in Model)
        {
            <li class='@if (parentNavigation.CurrentPage) {@Html.Raw("active")}'>
                <a href="@if (parentNavigation.Controller == null)
                         {
                             @Html.Raw("#")
                         }
                         else
                         {
                             @Url.Action(parentNavigation.Action, parentNavigation.Controller)
                         }">
                    <span class="glyphicons @parentNavigation.Icon"></span><span class="sidebar-title">@parentNavigation.Name</span>
                    @if (parentNavigation.ArraySubNavigationModels.Any())
                    {
                        <span class="caret"></span>
                    }
                </a>
                @if (parentNavigation.ArraySubNavigationModels.Any())
                {
                    <ul class="nav sub-nav @if (parentNavigation.CurrentPage)
                                           {@Html.Raw("menu-open collapsed")}">
                        @foreach (var subMenu in parentNavigation.ArraySubNavigationModels)
                        {
                            <li><a href="@Url.Action(subMenu.Action, subMenu.Controller)"><span class="glyphicons @subMenu.Icon"></span>@subMenu.Name</a></li>
                        }
                    </ul>
                }
            </li>
        }
    </ul>
</div>