Areas/Admin/Controllers/BannerSliderController.cs
#region

using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Common;
using Common.Models.Admin.ViewModel;
using Common.Providers.Files;
using Common.Providers.Logging;
using Common.Providers.Messages;
using Common.Providers.Roles;
using Common.Repositories;

#endregion

namespace Kapsters.Areas.Admin.Controllers
{
    public class BannerSliderController : ApplicationController
    {
        private BannerSliderRepository BannerSliderRepository { get; set; }

        public BannerSliderController()
        {
            BannerSliderRepository = new BannerSliderRepository();
        }

        [RolePermission(permissionName = RolePermission.PermissionName.BannerSlider)]
        public ActionResult _Weergeven()
        {
            var bannerSliderList = new Collection<ViewBannerSliderModel>();

            var bannerSliders = BannerSliderRepository.GetList();

            foreach (BannerSlider bannerSlider in bannerSliders)
            {
                bannerSliderList.Add(new ViewBannerSliderModel
                {
                    BannerSliderId = bannerSlider.BannerSliderId,
                    Description = bannerSlider.Description,
                    ImageName = bannerSlider.Image,
                    Title = bannerSlider.Title
                });
            }

            return View(bannerSliderList);
        }

        public ActionResult Weergeven()
        {
            return View();
        }

        [RolePermission(permissionName = RolePermission.PermissionName.BannerSlider)]
        public ActionResult Toevoegen()
        {
            return View();
        }

        [HttpPost]
        [RolePermission(permissionName = RolePermission.PermissionName.BannerSlider)]
        public ActionResult Toevoegen(BannerSliderModel addBannerSliderModel)
        {
            if (ModelState.IsValid)
            {
                using (var newBannerSliderRepository = new BannerSliderRepository())
                {
                   var bannerSlider = new BannerSlider
                    {
                        Description = addBannerSliderModel.Description,
                        Title = addBannerSliderModel.Title,
                        Image = FileProvider.GetNewImageName(addBannerSliderModel.Image)
                    };

                    newBannerSliderRepository.Add(bannerSlider);

                    newBannerSliderRepository.Save();

                    AddImage(addBannerSliderModel.Image, bannerSlider.BannerSliderId);
                }

                LogProvider.LogAction(
                    string.Format("De banner {0} is toegevoegd aan de slider", addBannerSliderModel.Image.FileName));

                this.SetSuccess("De afbeelding voor de slider is succesvol toegevoegd.");

                return RedirectToAction("Weergeven");
            }
            return View(addBannerSliderModel);
        }

        [RolePermission(permissionName = RolePermission.PermissionName.BannerSlider)]
        public ActionResult Wijzig(int id)
        {
            BannerSlider bannerSliderInfo = BannerSliderRepository.GetById(id);

            var bannerSliderModel = new BannerSliderModel
            {
                Description = bannerSliderInfo.Description,
                Title = bannerSliderInfo.Title,
                BannerSliderId = bannerSliderInfo.BannerSliderId
            };

            return View(bannerSliderModel);
        }

        [HttpPost]
        [RolePermission(permissionName = RolePermission.PermissionName.BannerSlider)]
        public ActionResult Wijzig(BannerSliderModel editBannerSliderModel)
        {
            if (ModelState.IsValid)
            {
                BannerSlider bannerSliderInfo = BannerSliderRepository.GetById(editBannerSliderModel.BannerSliderId);

                bannerSliderInfo.Description = editBannerSliderModel.Description;
                bannerSliderInfo.Title = editBannerSliderModel.Title;
                bannerSliderInfo.Image = editBannerSliderModel.Image != null ? FileProvider.GetNewImageName(editBannerSliderModel.Image) : bannerSliderInfo.Image;

                string oldImageName = bannerSliderInfo.Image;

                EditImage(editBannerSliderModel.BannerSliderId, editBannerSliderModel.Image);

                BannerSliderRepository.Save();

                LogProvider.LogAction(
                    string.Format("De banner {0} is gewijzigd in de slider", oldImageName));

                this.SetSuccess("De afbeelding voor de slider is succesvol gewijzigd.");

                return RedirectToAction("Weergeven");
            }

            return View(editBannerSliderModel);
        }


        [RolePermission(permissionName = RolePermission.PermissionName.BannerSlider)]
        public ActionResult Verwijder(int id)
        {
            BannerSlider bannerSliderInfo = BannerSliderRepository.GetById(id);

            if (bannerSliderInfo != null)
            {
                string fullPath = FileProvider.GetImagePath(Common.Providers.Files.FilePaths.Banners);

                // Remove old image   
                System.IO.File.Delete(fullPath + bannerSliderInfo.Image);

                // Remove in database
                BannerSliderRepository.Remove(bannerSliderInfo);

                BannerSliderRepository.Save();

                LogProvider.LogAction(
                    string.Format("De banner {0} is verwijderd in de slider", bannerSliderInfo.Image));

                this.SetSuccess("De afbeelding voor de slider is succesvol verwijderd.");
            }
            else
            {
                this.SetError("De afbeelding voor de slider is niet verwijderd want hij bestaat niet.");
            }

            return RedirectToAction("Weergeven");
        }

        #region Private Methods

        private void AddImage(HttpPostedFileBase postedFile, int bannerId)
        {
            FileProvider.AddFolderDirectory(FilePaths.Banners,
                bannerId.ToString(CultureInfo.InvariantCulture), false);

            FileProvider.AddAndReturnImageName(postedFile, FilePaths.Banners, bannerId.ToString(CultureInfo.InvariantCulture));
        }

        private void EditImage(int bannerSliderId, HttpPostedFileBase postedFile)
        {
            if (postedFile != null)
            {
                // Get banner info
                var bannerInfo = BannerSliderRepository.GetById(bannerSliderId);

                // Check if the news article exists
                if (bannerInfo != null)
                {
                    // Delete previous image
                    FileProvider.DeleteFile(FilePaths.Banners, bannerSliderId.ToString(CultureInfo.InvariantCulture),
                         bannerInfo.Image, false);

                    // Create directory
                    FileProvider.AddFolderDirectory(FilePaths.Banners, bannerSliderId.ToString(CultureInfo.InvariantCulture),
                        true);

                    // Save image
                    string fileName = FileProvider.AddAndReturnImageName(postedFile, FilePaths.Banners,
                        bannerSliderId.ToString(CultureInfo.InvariantCulture));

                    // Update banner
                    bannerInfo.Image = fileName;

                    // Save changes
                    BannerSliderRepository.Save();
                }
            }
        }
        #endregion
    }
}

Areas/Admin/Views/BannerSlider/Toevoegen.cshtml
@model Common.Models.Admin.ViewModel.BannerSliderModel

@{
    ViewBag.Title = "Afbeelding toevoegen";
}
<div class="col-md-12">
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <div class="panel-title">Afbeelding toevoegen</div>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("Toevoegen", "BannerSlider", FormMethod.Post, new {enctype = "multipart/form-data", id = "form"}))
                    {
                        <div class="form-group">
                            @Html.LabelFor(m => m.Title)
                            @Html.TextBoxFor(m => m.Title, new {@class = "form-control"})
                            @Html.ValidationMessageFor(m => m.Title)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Description)
                            @Html.TextAreaFor(m => m.Description, new {@class = "form-control", @rows = "3"})
                            @Html.ValidationMessageFor(m => m.Description)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Image)
                            @Html.TextBoxFor(m => m.Image, new {@type = "file", @multiple = "true"})
                            @Html.ValidationMessageFor(m => m.Image)
                        </div>

                        <input type="submit" value="Afbeelding toevoegen!" class="btn btn-info btn-gradient" />
                    }
                </div>

                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="@Url.Content("~/Areas/Admin/Content/js/fileButtonReplacer.js")"></script>
}

Areas/Admin/Views/BannerSlider/Weergeven.cshtml
<div id="viewContent" data-url="@Url.Action("_Weergeven")"></div>



@section Styles{
    @Styles.Render("~/Areas/Admin/Content/css/datatables")
}

@section Scripts{
@Scripts.Render("~/Areas/Admin/Content/js/datatables")
<script type="text/javascript">
    $(function () {
        $('#datatable').footable();
    });
</script>
}

Areas/Admin/Views/BannerSlider/Wijzig.cshtml
@model Common.Models.Admin.ViewModel.BannerSliderModel

<div class="col-md-12" id="bannerSlider">
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <div class="panel-title">Afbeelding wijzigen</div>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("Toevoegen", "BannerSlider", FormMethod.Post, new {enctype = "multipart/form-data", id = "form"}))
                    {
                        @Html.HiddenFor(m => m.BannerSliderId)

                        <div class="form-group">
                            @Html.LabelFor(m => m.Title)
                            @Html.TextBoxFor(m => m.Title, new {@class = "form-control"})
                            @Html.ValidationMessageFor(m => m.Title)
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Description)
                            @Html.TextAreaFor(m => m.Description, new {@class = "form-control", @rows = "3"})
                            @Html.ValidationMessageFor(m => m.Description)
                        </div>

                        <div class="form-group">
                            <div class="fullWidth">
                                <span class="info-icon tool-tip" data-toggle="tooltip" data-placement="right" title="Als u een nieuwe afbeelding kiest dan wordt de vorige verwijderd."></span>
                                @Html.LabelFor(m => m.Image, new { @class = "tooltip-label" })
                            </div>
                            @Html.TextBoxFor(m => m.Image, new {@type = "file"})
                            @Html.ValidationMessageFor(m => m.Image)
                        </div>

                        <input type="submit" value="Afbeelding toevoegen!" class="btn btn-info btn-gradient" />
                    }
                </div>

                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="@Url.Content("~/Areas/Admin/Content/js/fileButtonReplacer.js")"></script>
}